Use global stdin instead of local variable
The stdin bypass will use a local variable stdin instead of $stdin and
it will result in the following error:

Traceback (most recent call last):
	2: from /usr/lib/ruby/vendor_ruby/svn2git/migration.rb:432:in `block (2 levels) in run_command'
      	1: from /usr/lib/ruby/vendor_ruby/svn2git/migration.rb:432:in `loop'
/usr/lib/ruby/vendor_ruby/svn2git/migration.rb:438:in `block (3 levels) in run_command': undefined local variable or method `stdin' for #<Svn2Git::Migration:0x0000555b7c945cc8> (NameError)
Did you mean?  String

This fix should handle the error and uses the global stdin